"""
Agent logic for text-to-SQL conversion.
"""

import json
import sqlite3
from dataclasses import dataclass

from pydantic import ValidationError

from src.llm import LLM
from src.models import DEFAULT_MODEL
from src.tools import get_tool, tool_definitions
from src.turns import (
    AgentTurn,
    Conversation,
    SystemTurn,
    TextToSQLToolTurn,
    ToolTurn,
    Turn,
    UserTurn,
    to_messages,
)
from src.utils import get_ddl

SYSTEM_PROMPT = """
You are a SQL analyst answering questions about a SQLite database.
Only select the columns needed to answer the question.

Schema: {ddl}"""

# One call to write the SQL, up to two more to fix it, one to summarise the rows.
MAX_STEPS = 4

NO_ANSWER = "Sorry, I couldn't answer that one."


@dataclass
class Response:
    text: str
    latency_s: float
    cost_usd: float
    text_to_sql_tool_turn: TextToSQLToolTurn | None

    @staticmethod
    def from_conversation(
        conversation: Conversation, total_latency: float, total_cost_usd: float
    ):
        content = ""
        text_to_sql_tool_turn = None
        turns: list[Turn] = reversed(conversation)  # reverse chronology of turns

        for turn in turns:  # handle multiple tool calls
            if isinstance(turn, TextToSQLToolTurn):
                text_to_sql_tool_turn = turn
                break

        if isinstance(conversation[-1], AgentTurn):
            content += conversation[-1].raw_message.content

        return Response(
            text=content,
            latency_s=total_latency,
            cost_usd=total_cost_usd,
            text_to_sql_tool_turn=text_to_sql_tool_turn,
        )


class Agent:
    """A text-to-SQL agent holding one conversation against one database."""

    def __init__(
        self,
        conn: sqlite3.Connection,
        model: str = DEFAULT_MODEL,
        llm: LLM | None = None,
    ):
        self.conn = conn
        self.model = model
        self.llm = llm or LLM()
        self.conversation: Conversation = [
            SystemTurn(content=SYSTEM_PROMPT.format(ddl=get_ddl(self.conn)))
        ]

    def ask(self, question: str) -> Response:
        """Answer one question, appending every turn to the conversation."""
        self.conversation.append(UserTurn(question))
        turn_start = len(self.conversation)  # first turn generated by this call

        latency_s, cost_usd = 0.0, 0.0

        for _ in range(MAX_STEPS):
            turn = self.llm.chat(
                to_messages(self.conversation),
                model=self.model,
                tools=tool_definitions(),
                tool_choice="auto",
            )

            self.conversation.append(turn)  # agent turn
            latency_s += turn.latency_s
            cost_usd += turn.cost_usd

            if not turn.tool_calls:  # if it's not a tool call, return
                break

            tool_call = turn.tool_calls[0]  # fix me: handle multiple tool calls
            try:
                tool = get_tool(tool_call.function.name)
                args = tool.parse_tool_args(tool_call.function.arguments)
                result = tool.run(self.conn, args)
                self.conversation.append(tool.get_tool_turn(tool_call.id, result))
            except (json.JSONDecodeError, ValidationError) as e:
                error = json.dumps({"error": f"Malformed tool call: {e}"})
                self.conversation.append(
                    ToolTurn(tool_call_id=tool_call.id, content=error)
                )

        return Response.from_conversation(
            conversation=self.conversation[turn_start:],
            total_latency=latency_s,
            total_cost_usd=cost_usd,
        )
